export const AUTHORITIES = {
    CUSTOMER: "CUSTOMER",
    CUSTOMER_FREE: "CUSTOMER_FREE",
    CUSTOMER_PREMIUM: "CUSTOMER_PREMIUM",
    COMPANY: "COMPANY",
    COMPANY_FREE: "COMPANY_FREE",
    COMPANY_PREMIUM: "COMPANY_PREMIUM",
    ADMIN: "ADMIN",
    ANONYMOUS: "ANONYMOUS"
} as const;
  
export type AuthorityType = (typeof AUTHORITIES)[keyof typeof AUTHORITIES];